/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Action;
import javax.swing.Timer;

/**
 *
 * @author Miguel
 */
public class Ventana extends javax.swing.JFrame {

    private Timer tiempo;
    private int centesimaSegundo=0,segundos=0,minutos=0,horas=0;
    
    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            centesimaSegundo++;
            if(centesimaSegundo==100){
                segundos++;
                centesimaSegundo = 0;
            }
            if(segundos == 60){
                minutos++;
                segundos=0;
            }
            if(minutos == 60){
                horas++;
                minutos=0;
            }
            
            actualizarEtiquetaTiempo();
        }
    };
    
    private void actualizarEtiquetaTiempo(){
        String texto = (horas<=9?"0":"") + horas + ":"+(minutos <=9?"0":"") + minutos +":"+ (segundos<=9?"0":"")+ segundos+":"+ (centesimaSegundo<=9?"0":"") + centesimaSegundo;
        etiquetaTiempo.setText(texto);
    }
    
    
    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);
        tiempo = new Timer(10, acciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        imagenCronometro = new javax.swing.JLabel();
        tituloCronometro = new javax.swing.JLabel();
        etiquetaTiempo = new javax.swing.JLabel();
        botonInicar = new javax.swing.JButton();
        botonPausar = new javax.swing.JButton();
        botonDetener = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronometro");
        setResizable(false);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagenCronometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cronometro.png"))); // NOI18N
        imagenCronometro.setText("I");
        panel.add(imagenCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 150));

        tituloCronometro.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 30)); // NOI18N
        tituloCronometro.setForeground(new java.awt.Color(0, 0, 0));
        tituloCronometro.setText("Cronómetro");
        tituloCronometro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(tituloCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 190, 40));

        etiquetaTiempo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        etiquetaTiempo.setForeground(new java.awt.Color(0, 0, 0));
        etiquetaTiempo.setText("00:00:00:00");
        etiquetaTiempo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(etiquetaTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 220, 50));

        botonInicar.setBackground(new java.awt.Color(0, 153, 153));
        botonInicar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonInicar.setText("Iniciar");
        botonInicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicarActionPerformed(evt);
            }
        });
        panel.add(botonInicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 100, 40));

        botonPausar.setBackground(new java.awt.Color(0, 153, 153));
        botonPausar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonPausar.setText("Pausar");
        botonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPausarActionPerformed(evt);
            }
        });
        panel.add(botonPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 100, 40));

        botonDetener.setBackground(new java.awt.Color(0, 153, 153));
        botonDetener.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botonDetener.setText("Detener");
        botonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetenerActionPerformed(evt);
            }
        });
        panel.add(botonDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 100, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        panel.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPausarActionPerformed
        // TODO add your handling code here:
        
        tiempo.stop();
        botonInicar.setEnabled(true);
        botonPausar.setEnabled(false);
    }//GEN-LAST:event_botonPausarActionPerformed

    private void botonInicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicarActionPerformed
        tiempo.start();
        botonInicar.setEnabled(false);
        botonInicar.setText("Reanudar");
        botonPausar.setEnabled(true);
        botonDetener.setEnabled(true);
        
        
    }//GEN-LAST:event_botonInicarActionPerformed

    private void botonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetenerActionPerformed
        // TODO add your handling code here:
        if(tiempo.isRunning()){//Si el tiempo sigue corriendo
            tiempo.stop();
            botonInicar.setEnabled(true);
            
            
        }
        botonInicar.setText("Iniciar");
        botonPausar.setEnabled(false);
        
        botonDetener.setEnabled(false);
        
        horas = 0;
        minutos= 0;
        segundos = 0;
        centesimaSegundo = 0;
        
        actualizarEtiquetaTiempo();
        
    }//GEN-LAST:event_botonDetenerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDetener;
    private javax.swing.JButton botonInicar;
    private javax.swing.JButton botonPausar;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel imagenCronometro;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel tituloCronometro;
    // End of variables declaration//GEN-END:variables
}
